name = "ContACT"
uuid = "26035af4-eac7-442e-a6d9-7ff0777c6303"
version = "0.1.0"
authors = ["Simon Frost"]
description = "Applied category theory for structured contact matrices"
license = "MIT"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Catlab = "0.16, 0.17"
DataFrames = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
